---
    - hosts: all
      gather_facts: True
      tasks:
        - name: Check if ansible group exists
          getent:
            database: group
            key: "{{ lookup('env','ANSIBLE_GROUP') | default('deployer',true) }}"
            fail_key: yes
          register: group_exist
          ignore_errors: true
    
        - name: Check if ansible user exists
          getent:
            database: passwd
            key: "{{ lookup('env','ANSIBLE_USER') | default('deployer',true) }}"
            fail_key: yes
          register: user_exist
          ignore_errors: true
    
        - name: Create a ansible group
          group:
            name: "{{ lookup('env','ANSIBLE_GROUP') | default('deployer',true) }}"
            state: present
          when: group_exist["failed"] == true
          become: yes
    
        - name: Create a ansible user
          user:
            name: "{{ lookup('env','ANSIBLE_USER') | default('deployer',true) }}"
            groups: 
                - "{{ lookup('env','ANSIBLE_GROUP') | default('deployer',true) }}"
            state: present
            generate_ssh_key: "{{ 'yes' if ansible_connection == 'local' else 'no' }}"
            ssh_key_bits: 4096
            ssh_key_file: .ssh/id_rsa
            shell: /bin/bash       
            system: no        
            createhome: yes
            home: "/home/{{ lookup('env','ANSIBLE_USER') | default('deployer',true) }}"     # Defaults to /home/<username>
          register: ansible_user
          when: 
            - user_exist["failed"] == true
        
        - name: Ensure wheel group exists
          group:
            name: wheel
            state: present
          become: yes
    
        - name: Add ansible user to sudoers
          lineinfile:
            path: /etc/sudoers.d/90-ansible-user
            line: "{{ lookup('env','ANSIBLE_USER') | default('deployer',true) }} ALL=(ALL) NOPASSWD: ALL"
            state: present
            mode: 0440
            create: yes
            validate: 'visudo -cf %s'
          become: yes
    
        - name: Get ansible public key
          command: "cat {{ '/home/' + lookup('env','ANSIBLE_USER') | default('deployer',true) + '/.ssh/id_rsa.pub' }}"
          delegate_to: localhost
          become: yes
          become_user: "{{ lookup('env','ANSIBLE_USER') | default('deployer',true) }}"
          register: public_key

        - name: Add sudoers users to wheel group
          user: 
            name: "{{ lookup('env','ANSIBLE_USER') | default('deployer',true) }}" 
            groups: wheel 
            append: yes 
            state: present
            createhome: yes
          become: yes
    
        - name: Set up authorized keys for the ansible user
          authorized_key:
            user: "{{ lookup('env','ANSIBLE_USER') | default('deployer',true) }}"
            key: "{{ public_key.stdout }}"
            state: present
          
        - name: Delete stale lock files
          file:
            path: "{{ item }}"
            state: absent
          with_items:
            - /etc/passwd.lock
            - /etc/shadow.lock
            - /etc/group.lock
            - /etc/gshadow.lock